services:
  - type: web
    name: lost-found-tracking
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask db upgrade && gunicorn --worker-class eventlet -w 1 run:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_API_KEY
        sync: false
