"""Add plain_code_dev column to VerificationCode for dev testing

Revision ID: 261437bc199d
Revises: 66704c25bbad
Create Date: 2026-04-27 01:16:47.367628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261437bc199d'
down_revision = '66704c25bbad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plain_code_dev', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_code', schema=None) as batch_op:
        batch_op.drop_column('plain_code_dev')

    # ### end Alembic commands ###
