"""Add user encryption with RSA and ECC keypairs, and PBKDF2 password hashing

Revision ID: 3173248b4d6e
Revises: 366337292924
Create Date: 2026-04-27 00:39:35.361376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3173248b4d6e'
down_revision = '366337292924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rsa_public_key', sa.Text(), nullable=False),
    sa.Column('rsa_private_key', sa.Text(), nullable=False),
    sa.Column('ecc_public_key', sa.Text(), nullable=False),
    sa.Column('ecc_private_key', sa.Text(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('rotated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('email_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contact_info_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('name_hmac', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('email_hmac', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('contact_info_hmac', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('password_salt', sa.String(length=256), nullable=True))
        batch_op.drop_column('contact_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_info', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('password_salt')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('contact_info_hmac')
        batch_op.drop_column('email_hmac')
        batch_op.drop_column('name_hmac')
        batch_op.drop_column('contact_info_encrypted')
        batch_op.drop_column('email_encrypted')
        batch_op.drop_column('name_encrypted')

    op.drop_table('user_keys')
    # ### end Alembic commands ###
