"""Added contributor attribute to user model

Revision ID: 366337292924
Revises: dfba6b33bfaa
Create Date: 2025-05-09 23:35:30.733422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366337292924'
down_revision = 'dfba6b33bfaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contribution', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('contribution')

    # ### end Alembic commands ###
