"""Add two-factor authentication with OTP verification codes

Revision ID: 66704c25bbad
Revises: 3173248b4d6e
Create Date: 2026-04-27 00:57:46.015422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66704c25bbad'
down_revision = '3173248b4d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=256), nullable=False),
    sa.Column('code_salt', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_code')
    # ### end Alembic commands ###
