"""Add encryption fields to Post model for requirement 6

Revision ID: 8a7c9d1e2f3a
Revises: 47c8b3f5a9d2
Create Date: 2026-05-07 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a7c9d1e2f3a'
down_revision = '47c8b3f5a9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('item_name_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('location_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contact_method_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_hmac', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('item_name_hmac', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('location_hmac', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('contact_method_hmac', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('contact_method_hmac')
        batch_op.drop_column('location_hmac')
        batch_op.drop_column('item_name_hmac')
        batch_op.drop_column('description_hmac')
        batch_op.drop_column('contact_method_encrypted')
        batch_op.drop_column('location_encrypted')
        batch_op.drop_column('item_name_encrypted')
        batch_op.drop_column('description_encrypted')

    # ### end Alembic commands ###
