"""Add encryption fields to Chat model for secure messaging

Revision ID: 9b8c7d6e5f4a
Revises: 8a7c9d1e2f3a
Create Date: 2026-05-07 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b8c7d6e5f4a'
down_revision = '8a7c9d1e2f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        # Add encrypted message field
        batch_op.add_column(sa.Column('message_encrypted', sa.Text(), nullable=True))
        # Add HMAC tag for integrity verification
        batch_op.add_column(sa.Column('message_hmac', sa.String(length=256), nullable=True))
        # Make original message column nullable for backward compatibility
        batch_op.alter_column('message', existing_type=sa.Text(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        # Restore message column to non-nullable
        batch_op.alter_column('message', existing_type=sa.Text(), nullable=False)
        # Remove HMAC tag column
        batch_op.drop_column('message_hmac')
        # Remove encrypted message column
        batch_op.drop_column('message_encrypted')

    # ### end Alembic commands ###
